from pathlib import Path
from datetime import datetime
ROOT=Path(__file__).resolve().parent
INDEX=next((x for x in (ROOT/'index.html',ROOT/'static'/'index.html') if x.exists()),None)
if not INDEX: raise SystemExit('ERROR: index.html not found')
h=INDEX.read_text(encoding='utf-8')
if 'PP_IMAGE_STUDIO_2_0_STAGE3_CSS' not in h: raise SystemExit('ERROR: Stage 3 marker not found')
if 'PP_IMAGE_STUDIO_2_0_STAGE4_CSS' in h: print('IMAGE_STUDIO_2_0_STAGE4_ALREADY_APPLIED'); raise SystemExit
b=INDEX.with_name('index_before_image_studio_2_0_stage4_'+datetime.now().strftime('%Y%m%d_%H%M%S')+'.html'); b.write_text(h,encoding='utf-8')
css='''<style id="pp-image-studio-stage4-css">/* PP_IMAGE_STUDIO_2_0_STAGE4_CSS */\n.pp-s4-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.pp-s4-control{display:flex;align-items:center;gap:8px;margin:7px 0}.pp-s4-control label{min-width:88px;font-size:12px}.pp-s4-control input[type=range]{flex:1}.pp-s4-value{width:42px;text-align:right;font-size:11px;opacity:.75}.pp-s4-btn{border:1px solid var(--border,#d8dde6);border-radius:7px;background:var(--card,#fff);padding:7px;cursor:pointer}@media(max-width:800px){.pp-s4-grid{grid-template-columns:1fr}}</style>'''
h=h.replace('</head>',css+'</head>',1)
adj='''<div class="tool-section" id="ppImgStage4Adjustments"><h4>Advanced Adjustments</h4><div class="pp-s4-grid"><div><div class="pp-s4-control"><label>Exposure</label><input id="ppS4Exposure" type="range" min="-100" max="100" value="0"><span id="ppS4ExposureV" class="pp-s4-value">0</span></div><div class="pp-s4-control"><label>Highlights</label><input id="ppS4Highlights" type="range" min="-100" max="100" value="0"><span id="ppS4HighlightsV" class="pp-s4-value">0</span></div><div class="pp-s4-control"><label>Shadows</label><input id="ppS4Shadows" type="range" min="-100" max="100" value="0"><span id="ppS4ShadowsV" class="pp-s4-value">0</span></div><div class="pp-s4-control"><label>Vibrance</label><input id="ppS4Vibrance" type="range" min="-100" max="100" value="0"><span id="ppS4VibranceV" class="pp-s4-value">0</span></div></div><div><div class="pp-s4-control"><label>Temperature</label><input id="ppS4Temperature" type="range" min="-100" max="100" value="0"><span id="ppS4TemperatureV" class="pp-s4-value">0</span></div><div class="pp-s4-control"><label>Tint</label><input id="ppS4Tint" type="range" min="-100" max="100" value="0"><span id="ppS4TintV" class="pp-s4-value">0</span></div><div class="pp-s4-control"><label>Gamma</label><input id="ppS4Gamma" type="range" min="-100" max="100" value="0"><span id="ppS4GammaV" class="pp-s4-value">0</span></div><div class="pp-s4-control"><label>Sharpness</label><input id="ppS4Sharpness" type="range" min="0" max="100" value="0"><span id="ppS4SharpnessV" class="pp-s4-value">0</span></div></div></div><div class="pp-s4-control"><label>Fade</label><input id="ppS4Fade" type="range" min="0" max="100" value="0"><span id="ppS4FadeV" class="pp-s4-value">0</span></div><button class="pp-s4-btn" type="button" onclick="ppImgS4ResetAdjustments()">Reset adjustments</button></div>'''
if '<h4>Filters</h4>' in h: h=h.replace('<h4>Filters</h4>',adj+'<h4>Filters</h4>',1)
js='''<script id="pp-image-studio-stage4-js">/* PP_IMAGE_STUDIO_2_0_STAGE4_JS */(function(){"use strict";const $=id=>document.getElementById(id),ids=["Exposure","Highlights","Shadows","Vibrance","Temperature","Tint","Gamma","Sharpness","Fade"];function sync(){ids.forEach(k=>{let a=$("ppS4"+k),v=$("ppS4"+k+"V");if(a&&v)v.textContent=a.value})}function render4(){let c=window.ppImgCanvas,base=window.ppImgBaseCanvas;if(!c||!base)return;let x=c.getContext("2d"),a={};ids.forEach(k=>a[k.toLowerCase()]=+($("ppS4"+k)?.value||0));x.clearRect(0,0,c.width,c.height);x.drawImage(base,0,0);let im=x.getImageData(0,0,c.width,c.height),d=im.data,ex=Math.pow(2,a.exposure/100),ga=1/(1+a.gamma/100),t=a.temperature/100,ti=a.tint/100,vi=a.vibrance/100;for(let i=0;i<d.length;i+=4){let r=d[i],g=d[i+1],b=d[i+2],l=.2126*r+.7152*g+.0722*b,hi=Math.max(0,(l-128)/127),sh=Math.max(0,(128-l)/128);r=(r-128)*ex+128+a.highlights/100*hi*45+a.shadows/100*sh*45;g=(g-128)*ex+128+a.highlights/100*hi*45+a.shadows/100*sh*45;b=(b-128)*ex+128+a.highlights/100*hi*45+a.shadows/100*sh*45;let mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx?((mx-mn)/mx):0,v=1+vi*(1-sat);r=128+(r-128)*v;g=128+(g-128)*v;b=128+(b-128)*v;r+=t*22-ti*8;g+=ti*10;b-=t*22-ti*8;r=255*Math.pow(Math.max(0,Math.min(255,r))/255,ga);g=255*Math.pow(Math.max(0,Math.min(255,g))/255,ga);b=255*Math.pow(Math.max(0,Math.min(255,b))/255,ga);let f=a.fade/100;d[i]=r*(1-f)+255*f;d[i+1]=g*(1-f)+255*f;d[i+2]=b*(1-f)+255*f}x.putImageData(im,0,0);if(typeof window.ppImgRender==="function")window.ppImgRender()}window.ppImgS4ResetAdjustments=function(){ids.forEach(k=>{let x=$("ppS4"+k);if(x)x.value=0});sync();render4()};ids.forEach(k=>{let x=$("ppS4"+k);if(x)x.addEventListener("input",()=>{sync();render4()})});sync()})();</script>'''
h=h.replace('</body>',js+'</body>',1);INDEX.write_text(h,encoding='utf-8')
print('IMAGE_STUDIO_2_0_STAGE4_APPLIED');print('backup:',b.name);print('index.html bytes:',INDEX.stat().st_size)
for k,v in {'STAGE4_CSS':'PP_IMAGE_STUDIO_2_0_STAGE4_CSS' in h,'STAGE4_JS':'PP_IMAGE_STUDIO_2_0_STAGE4_JS' in h,'ADVANCED_ADJUSTMENTS':'ppS4Exposure' in h,'TEMPERATURE':'ppS4Temperature' in h,'VIBRANCE':'ppS4Vibrance' in h,'SHARPNESS':'ppS4Sharpness' in h}.items():print(k+':','PASS' if v else 'FAIL')
print('main.py was NOT modified.');print('Security/backend/annotation/batch untouched.');print('IMAGE STUDIO 2.0 STAGE 4 COMPLETE')
